# Generated by Django 5.0.3 on 2024-04-16 23:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('short_name', models.CharField(blank=True, max_length=255)),
                ('mascot', models.CharField(blank=True, max_length=255)),
                ('mail_domains', models.JSONField(blank=True, default=list)),
                ('mail_tag', models.CharField(blank=True, default='+', help_text='The tag separator used in school emails, if any.', max_length=1)),
                ('mail_dots', models.BooleanField(default=True, help_text='Whether to remove dots from the local part of school emails.')),
            ],
        ),
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(blank=True, choices=[('image/png', 'Png'), ('image/jpeg', 'Jpeg'), ('image/gif', 'Gif'), ('image/svg+xml', 'Svg')], max_length=255)),
                ('data', models.BinaryField(blank=True)),
                ('bg_color', models.CharField(default='#0000ff', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9a-fA-F]{6}$', 'Enter a valid hex color, like #000000.')])),
                ('action_color', models.CharField(default='#ff0000', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9a-fA-F]{6}$', 'Enter a valid hex color, like #000000.')])),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='logo', to='vb.school')),
            ],
        ),
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('amount', models.IntegerField(default=5, help_text='The USD amount of the gift card.')),
                ('name_template', models.TextField(default='${{ contest.amount }} Amazon Gift Card Giveaway', help_text='The name of the contest. Can use template variables like {{ school.name }} and {{ contest.amount }}.', max_length=255)),
                ('description_template', models.TextField(default='{{ school.short_name }} students: check your voter registration to win a ${{ contest.amount }} Amazon gift card.', help_text='A description of the contest. Can use template variables like {{ school.name }} and {{ contest.amount }}.')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contests', to='vb.school')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(help_text='The first email address we ever saw for this user.', max_length=254, unique=True)),
                ('hash', models.CharField(help_text='A unique ID for the student derived from their email address.', max_length=64, unique=True)),
                ('other_emails', models.JSONField(blank=True, default=list, help_text='The second (and beyond) emails for this user.')),
                ('email_validated_at', models.DateTimeField(blank=True, default=None, help_text='The time the email was validated.', null=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, default='', max_length=255)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='vb.school')),
            ],
        ),
        migrations.CreateModel(
            name='GiftCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('amount', models.IntegerField(help_text='The USD amount of the gift card.')),
                ('creation_request_id', models.CharField(help_text='The creation code for the gift card.', max_length=255, unique=True)),
                ('email_sent_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gift_cards', to='vb.contest')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gift_cards', to='vb.student')),
            ],
        ),
        migrations.AddConstraint(
            model_name='giftcard',
            constraint=models.UniqueConstraint(fields=('student', 'contest'), name='unique_student_contest_gift_card'),
        ),
    ]
