# Generated by Django 5.0.3 on 2024-03-29 18:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('short_name', models.CharField(blank=True, max_length=255)),
                ('mascot', models.CharField(blank=True, max_length=255)),
                ('mail_domains', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(blank=True, choices=[('image/png', 'Png'), ('image/jpeg', 'Jpeg'), ('image/gif', 'Gif'), ('image/svg+xml', 'Svg')], max_length=255)),
                ('data', models.BinaryField(blank=True)),
                ('bg_color', models.CharField(default='#0000ff', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9a-fA-F]{6}$', 'Enter a valid hex color, like #000000.')])),
                ('action_color', models.CharField(default='#ff0000', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9a-fA-F]{6}$', 'Enter a valid hex color, like #000000.')])),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='logo', to='vb.school')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vb.school')),
            ],
        ),
    ]
