# Generated by Django 5.0.3 on 2024-04-02 21:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('short_name', models.CharField(blank=True, max_length=255)),
                ('mascot', models.CharField(blank=True, max_length=255)),
                ('mail_domains', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(blank=True, choices=[('image/png', 'Png'), ('image/jpeg', 'Jpeg'), ('image/gif', 'Gif'), ('image/svg+xml', 'Svg')], max_length=255)),
                ('data', models.BinaryField(blank=True)),
                ('bg_color', models.CharField(default='#0000ff', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9a-fA-F]{6}$', 'Enter a valid hex color, like #000000.')])),
                ('action_color', models.CharField(default='#ff0000', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9a-fA-F]{6}$', 'Enter a valid hex color, like #000000.')])),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='logo', to='vb.school')),
            ],
        ),
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('template', models.TextField(default='{{ school.short_name }} students: check your voter registration for a 1 in 10 chance to win a $25 Amazon gift card.', help_text="A description of the contest. Can use {{ school.name }} to insert the school's name, etc.")),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contests', to='vb.school')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vb.school')),
            ],
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taken_at', models.DateTimeField(auto_now_add=True)),
                ('kind', models.CharField(choices=[('first_visit', 'First Visit'), ('check_registration', 'Check Registration'), ('register', 'Register')])),
                ('contest', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='vb.contest')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vb.student')),
            ],
        ),
    ]
