# Generated by Django 5.0.3 on 2024-04-18 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email_validated_at',
            field=models.DateTimeField(blank=True, db_index=True, default=None, help_text='The time the email was validated.', null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='other_emails',
            field=models.JSONField(blank=True, default=list, help_text='The second+ emails for this user. These may not be validated.'),
        ),
        migrations.CreateModel(
            name='EmailValidationLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='The specific email address to be validated.', max_length=254)),
                ('token', models.CharField(help_text='The current validation token, if any.', max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The time the email validation link was most recently created.')),
                ('consumed_at', models.DateTimeField(blank=True, default=None, help_text='The time the email validation link was first consumed.', null=True)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_validation_links', to='vb.contest')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_validation_links', to='vb.student')),
            ],
        ),
        migrations.AddConstraint(
            model_name='emailvalidationlink',
            constraint=models.UniqueConstraint(fields=('student', 'contest'), name='unique_student_contest_email_validation_link'),
        ),
    ]
