# Generated by Django 5.0.3 on 2024-04-24 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vb', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GiftCard',
            new_name='ContestEntry',
        ),
        migrations.AddField(
            model_name='contest',
            name='in_n',
            field=models.IntegerField(default=1, help_text='1 in_n students will win a gift card.'),
        ),
    ]
