# Generated by Django 5.0.3 on 2024-04-25 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vb', '0002_rename_gift_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestentry',
            name='amount',
            field=models.IntegerField(default=0, help_text='The USD amount of the gift card. 0 means no gift card.'),
        ),
        migrations.AlterField(
            model_name='contestentry',
            name='creation_request_id',
            field=models.CharField(blank=True, default='', help_text='The creation code for the gift card, if a prize was won..', max_length=255),
        ),
    ]
