# Generated by Django 5.0.3 on 2024-04-25 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vb', '0003_allow_for_no_prize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestentry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
