# Generated by Django 5.0.3 on 2024-04-25 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vb', '0004_index_contest_entry_times'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestentry',
            name='contest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contest_entries', to='vb.contest'),
        ),
        migrations.AlterField(
            model_name='contestentry',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contest_entries', to='vb.student'),
        ),
    ]
