# Generated by Django 5.0.3 on 2024-04-25 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vb', '0006_alter_contestentry_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailvalidationlink',
            name='contest',
        ),
        migrations.RemoveField(
            model_name='emailvalidationlink',
            name='school',
        ),
        migrations.AddField(
            model_name='contestentry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='emailvalidationlink',
            name='contest_entry',
            field=models.ForeignKey(blank=True, default=None, help_text='The contest entry, if any, associated with this email validation link.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_validation_links', to='vb.contestentry'),
        ),
        migrations.AlterField(
            model_name='contestentry',
            name='amount',
            field=models.IntegerField(default=0, help_text='The USD amount of the gift card. 0 means no winnings.'),
        ),
        migrations.AlterField(
            model_name='contestentry',
            name='creation_request_id',
            field=models.CharField(blank=True, default='', help_text='The creation code for the gift card, if a prize was issued.', max_length=255),
        ),
        migrations.AlterField(
            model_name='student',
            name='email_validated_at',
            field=models.DateTimeField(blank=True, db_index=True, default=None, help_text='The first time *any* email for this student was validated.', null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='other_emails',
            field=models.JSONField(blank=True, default=list, help_text='The second+ emails for this user. These *are* validated.'),
        ),
    ]
