# Generated by Django 5.0.3 on 2024-04-26 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vb', '0007_remove_emailvalidationlink_contest_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contestentry',
            old_name='amount',
            new_name='amount_won',
        ),
    ]
