# Generated by Django 5.0.3 on 2024-04-26 18:18

from django.db import migrations, models


def update_roll_values(apps, schema_editor):
    ContestEntry = apps.get_model("vb", "ContestEntry")
    for entry in ContestEntry.objects.all():
        if entry.amount_won == 0 and entry.roll == 0:
            # Just in case we have test data lying around, we'll make sure
            # roll and amount_won are consistent. NOTE well that this isn't
            # a real roll; it's just a placeholder. This should not impact
            # any production data, since as of this writing all production
            # contest entries are wins!
            entry.roll = 1
            entry.save()


class Migration(migrations.Migration):

    dependencies = [
        ('vb', '0008_amount_to_won'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestentry',
            name='roll',
            field=models.IntegerField(db_index=True, default=0, help_text='The result of the entry dice roll. 0 is a win.'),
            preserve_default=False,
        ),
        migrations.RunPython(update_roll_values, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='contestentry',
            name='amount_won',
            field=models.IntegerField(default=0, help_text='The USD amount won.'),
        ),
    ]
