# Generated by Django 5.0.3 on 2024-05-17 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vb', '0012_add_percent_voted'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='allow_subdomains',
            field=models.BooleanField(default=True, help_text='Whether to allow arbitrary subdomains in school emails.'),
        ),
    ]
