# Generated by Django 5.0.3 on 2024-05-21 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vb', '0013_add_subdomains_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='tool',
            field=models.CharField(choices=[('vote_america', 'Vote America'), ('rock_the_vote', 'Rock the Vote')], default='vote_america', max_length=32),
        ),
    ]
